# Generated by Django 5.1 on 2024-09-09 14:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_orders', models.IntegerField()),
                ('new_customers', models.IntegerField()),
                ('total_cart_abandons', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodicKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_orders', models.IntegerField()),
                ('total_acquisition_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_repeats', models.IntegerField(default=0)),
                ('lost_customers', models.IntegerField(default=0)),
                ('total_unique_customers', models.IntegerField(default=0)),
                ('average_inventory', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Periodic KPI',
                'verbose_name_plural': 'Periodic KPIs',
            },
        ),
    ]
