# Generated by Django 5.1 on 2024-09-09 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KPIs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodickpi',
            name='total_acquisition_cost',
        ),
    ]
